
server:
  port: 8017
  servlet:
    context-path: /


spring:
  datasource:
    url: jdbc:mysql://47.107.227.121:3306/cpe_project2?allowMultiQueries=true
    username: root
    password: sxzt888888
    driver-class-name:  com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

projectHttp: "Http://localhost:8088"

#如果数据为空的字段，则该字段省略不显示，可以通过添加配置文件，规定查询数据为空是则返回null。
mybatis:
  configuration:
    call-setters-on-nulls: true







